# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-dockerfile
build_from:
  aarch64: "ghcr.io/home-assistant/aarch64-base:3.22"
  amd64: "ghcr.io/home-assistant/amd64-base:3.22"
  armhf: "ghcr.io/home-assistant/armhf-base:3.22"
  armv7: "ghcr.io/home-assistant/armv7-base:3.22"
  i386: "ghcr.io/home-assistant/i386-base:3.22"
labels:
  org.opencontainers.image.title: "escpos2mqtt HomeAssistant Add-on"
  org.opencontainers.image.description: "Add-on to use ESC/POS thermal printers via MQTT."
  org.opencontainers.image.source: "https://github.com/jhbruhn/escpos2mqtt-hassio"
  org.opencontainers.image.licenses: "MIT"
args:
  TEMPIO_VERSION: "2024.11.2"
