# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: escpos2mqtt
version: "edge"
slug: escpos2mqtt
description: escpos2mqtt add-on
url: "https://github.com/jhbruhn/escpos2mqtt"
arch:
  - armv7
  - aarch64
  - amd64
init: false
#map:
#  - share:rw
options:
  printer_host: ""
  printer_name: "printer"
  printer_model: "TM-T88V"
schema:
  printer_host: "str"
  printer_name: "str?"
  printer_model: "str?"
services:
  - mqtt:need
image: "ghcr.io/jhbruhn/{arch}-escpos2mqtt-hassio"
