# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: escpos2mqtt
version: "0.1.9"
slug: escpos2mqtt
description: escpos2mqtt add-on
url: "https://github.com/jhbruhn/escpos2mqtt"
arch:
  - armv7
  - aarch64
  - amd64
init: false
#map:
#  - share:rw
options:
  printer_host: ""
  printer_name: "printer"
schema:
  printer_host: "str"
  printer_name: "str?"
  printer_dpi: "float?"
  printer_chars_per_line: "int?"
  printer_pixels_per_char: "int?"
services:
  - mqtt:need
image: "ghcr.io/jhbruhn/{arch}-escpos2mqtt-hassio"
